---
title: "Kmeans clustering"
author: "Vihari Konda"
date: "7/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) 
library(cluster)    
library(factoextra)
library(gridExtra)
```

```{r}
df <- USArrests # Loading out of the box dataset
df <- na.omit(df) # Removing NA values
df <- scale(df) # Standardising the data 
head(df) 
```

# Computing distant matrix and Visualising distance matrix
```{r}
distance <- get_dist(df) # 
fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07")) 

```

```{r}
k2 <- kmeans(df, centers = 2, nstart = 25) # Computing k-means 
str(k2)
```

```{r}
fviz_cluster(k2, data = df)
```

```{r}
df %>%
  as_tibble() %>%
  mutate(cluster = k2$cluster,
         state = row.names(USArrests)) %>%
  ggplot(aes(UrbanPop, Murder, color = factor(cluster), label = state)) +
  geom_text() 
```

```{r}
k3 <- kmeans(df, centers = 3, nstart = 25)
k4 <- kmeans(df, centers = 4, nstart = 25)
k5 <- kmeans(df, centers = 5, nstart = 25)
```

```{r}
# data plots to compare
p1 <- fviz_cluster(k2, geom = "point", data = df) + ggtitle("k = 2")
p2 <- fviz_cluster(k3, geom = "point",  data = df) + ggtitle("k = 3")
p3 <- fviz_cluster(k4, geom = "point",  data = df) + ggtitle("k = 4")
p4 <- fviz_cluster(k5, geom = "point",  data = df) + ggtitle("k = 5")
```

```{r}
grid.arrange(p1, p2, p3, p4, nrow = 2)
set.seed(123)
```

```{r}
wss <- function(k) {
  kmeans(df, k, nstart = 10 )$tot.withinss
}
# Compute and plot wss for k = 1 to k = 15
k.values <- 1:15
# extract wss for 2-15 clusters
wss_values <- map_dbl(k.values, wss)
```

```{r}
plot(k.values, wss_values,
       type="b", pch = 19, frame = FALSE, 
       xlab="Number of clusters K",
       ylab="Total within-clusters sum of squares")
set.seed(123)
```

```{r}
fviz_nbclust(df, kmeans, method = "wss")
```

```{r}
# function to compute average silhouette for k clusters
avg_sil <- function(k) {
  km.res <- kmeans(df, centers = k, nstart = 25)
  ss <- silhouette(km.res$cluster, dist(df))
  mean(ss[, 3])
}

# Compute and plot wss for k = 2 to k = 15
k.values <- 2:15
# extract avg silhouette for 2-15 clusters
avg_sil_values <- map_dbl(k.values, avg_sil)
```

```{r}
plot(k.values, avg_sil_values,
       type = "b", pch = 19, frame = FALSE, 
       xlab = "Number of clusters K",
       ylab = "Average Silhouettes")
```

```{r}
set.seed(123)
gap_stat <- clusGap(df, FUN = kmeans, nstart = 25,
                    K.max = 10, B = 50)
```

```{r}
# Print the result
print(gap_stat, method = "firstmax")
```

```{r}
fviz_gap_stat(gap_stat)
```
```{r}
set.seed(123)
final <- kmeans(df, 4, nstart = 25)
print(final)
```

```{r}
fviz_cluster(final, data = df)
```

```{r} 
USArrests %>%
  mutate(Cluster = final$cluster) %>%
  group_by(Cluster) %>%
  summarise_all("mean")
```

